/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.Controlador;
import Modelo.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Inaki
 */
public class NuevaReserva extends javax.swing.JFrame {
    
    Controlador controlador = new Controlador();
   
    public NuevaReserva(Controlador importado) {

        controlador.setListas(importado.getListas());
        importado = controlador;
        initComponents();
        
        getRootPane().setDefaultButton(this.jButton1);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Cancel"); //$NON-NLS-1$
        getRootPane().getActionMap().put("Cancel", new AbstractAction()
        { 

            public void actionPerformed(ActionEvent e)
            {
                dispose();
            }
       });

        this.jComboBox1.addItem("");
        this.jComboBox2.addItem("");
        this.jComboBox2.addItem("");
        this.jComboBox3.addItem("");
        this.jComboBox4.addItem("");
        this.jComboBox5.addItem("");
        this.jButton1.setEnabled(false);
        
        this.jLabel10.setVisible(false);
        this.jLabel11.setVisible(false);
        this.jLabel12.setVisible(false);
        this.jLabel13.setVisible(false);
        
        for(Marca marca: controlador.getListas().getListaDeMarcas()){
            this.jComboBox1.addItem(marca.getMarca());
        }
        
        this.jComboBox5.removeAllItems();
        this.jComboBox5.addItem("");
        
        for(Cliente cliente: controlador.getListas().getListaDeClientes()){
            this.jComboBox5.addItem(cliente.getNombre() + " " + cliente.getApellido());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Multimarca");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservas de Vehiculos");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione marca:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione modelo:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Seleccione versión:");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione color:");

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Fecha de reserva:");
        jLabel8.setToolTipText("");

        jTextField3.setToolTipText("Fecha");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Reservar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("(DD/MM/AAAA)");
        jLabel18.setToolTipText("");
        jLabel18.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Cliente:");

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Precio flete:");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Precio unidad:");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Precio patente:");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Precio total:");
        jLabel13.setToolTipText("");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Salir");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(12, 12, 12)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(295, 295, 295)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if(this.jComboBox1.getSelectedItem() == null){
            this.jButton1.setEnabled(false);
            this.jLabel9.setText("");
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox2.setSelectedIndex(0);
                this.jComboBox2.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            return;
        }
        if(this.jComboBox1.getSelectedItem().equals("")){
            this.jButton1.setEnabled(false);
            this.jLabel9.setText("");
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox2.setSelectedIndex(0);
                this.jComboBox2.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            return;
        }
        
        this.jComboBox2.setEnabled(true);
        
        this.jComboBox2.removeAllItems();
        this.jComboBox2.addItem("");
        
       for(Modelo modelo: controlador.getListas().getListaDeModelos()){
           if (modelo.getMarca().getMarca().equals(this.jComboBox1.getSelectedItem())){
               this.jComboBox2.addItem(modelo.getModelo());
           }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
        if(this.jComboBox2.getSelectedItem() == null){
            this.jButton1.setEnabled(false);
            this.jLabel9.setText("");
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            return;
        }
        
        if(this.jComboBox2.getSelectedItem().equals("")){
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            return;
        }
        
        this.jLabel4.setVisible(true);
        this.jComboBox3.setVisible(true);
        this.jComboBox3.setEnabled(true);
        
        this.jComboBox3.removeAllItems();
        this.jComboBox3.addItem("");
        
        for(Version version: controlador.getListas().getListaDeVersiones()){
            if(version.getModelo().getMarca().getMarca().equals(this.jComboBox1.getSelectedItem())){
                if(version.getModelo().getModelo().equals(this.jComboBox2.getSelectedItem())){
                    this.jComboBox3.addItem(version.getDescripcion());
                }
            }
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
       if(this.jComboBox3.getSelectedItem() == null){
           this.jButton1.setEnabled(false);
           this.jLabel10.setVisible(false);
           this.jLabel11.setVisible(false);
           this.jLabel12.setVisible(false);
           this.jLabel13.setVisible(false);
           try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
           this.jLabel9.setText("");
            return;
        }
       else this.jButton1.setEnabled(true);
        
        if(this.jComboBox3.getSelectedItem().equals("")){
            this.jButton1.setEnabled(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}

            this.jLabel9.setText("");
            return;
        }
        
        this.jLabel5.setVisible(true);
        this.jComboBox4.setVisible(true);
        this.jComboBox4.setEnabled(true);
        
        this.actualizarColores();
        
        String segmento = "";
        
        for(Version version: controlador.getListas().getListaDeVersiones()){
            if(version.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                segmento = version.getSegmento().getSegmento();
                break;
            }
        }
        
        this.jLabel9.setText("Segmento '" + segmento + "'");
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(this.jComboBox4.getSelectedItem() == null){
            this.jButton1.setEnabled(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            this.jLabel9.setText("");
            return;
        }
        
        if(this.jComboBox4.getSelectedItem().equals("")){
            this.jButton1.setEnabled(false);
            this.jLabel9.setText("");
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            return;
        }
      
        this.jLabel10.setVisible(true);
        this.jLabel11.setVisible(true);
        this.jLabel12.setVisible(true);
        this.jLabel13.setVisible(true);
        
        for(Version version: controlador.getListas().getListaDeVersiones()){
            if(version.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                double total = version.getSegmento().getPatentamiento() + version.getSegmento().getCostoFlete() + version.getPrecioUnidad();
                this.jLabel11.setText("Precio unidad: $" + version.getPrecioUnidad());
                this.jLabel12.setText("Precio patente: $" + version.getSegmento().getPatentamiento());
                this.jLabel10.setText("Precio flete: $" + version.getSegmento().getCostoFlete());
                this.jLabel13.setText("Precio total: $" + total);
            }
        }
        
        this.jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String formatoFecha = this.jTextField3.getText();
        
        Fecha fecha = new Fecha();
        
        if(!fecha.formato(formatoFecha)){
            JOptionPane.showMessageDialog(rootPane, "Fecha incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Marca marca = new Marca();
        Modelo modelo = new Modelo();
        Version version = new Version();
        Segmento segmento = new Segmento();
        Color color = new Color();
        Cliente cliente = new Cliente();
        
        for(Marca marcaDeLista: controlador.getListas().getListaDeMarcas()){
            if(marcaDeLista.getMarca().equals(this.jComboBox1.getSelectedItem())){
                marca.setMarca(marcaDeLista.getMarca());
                break;
            }
        }
        
        for(Modelo modeloDeLista: controlador.getListas().getListaDeModelos()){
            if(modeloDeLista.getModelo().equals(this.jComboBox2.getSelectedItem())){
                modelo.setMarca(marca);
                modelo.setModelo(modeloDeLista.getModelo());
                break;
            }
        }
        
        for(Version versionDeLista: controlador.getListas().getListaDeVersiones()){
            if(versionDeLista.getModelo().getMarca().getMarca().equals(this.jComboBox1.getSelectedItem())){
                if(versionDeLista.getModelo().getModelo().equals(this.jComboBox2.getSelectedItem())){
                    if(versionDeLista.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                        version.setDescripcion(versionDeLista.getDescripcion());
                        version.setModelo(versionDeLista.getModelo());
                        version.setPrecioUnidad(versionDeLista.getPrecioUnidad());
                        version.setSegmento(versionDeLista.getSegmento());
                        version.setColores(versionDeLista.getColores());
//                        version.calcularPatentamiento();
                        break;
                    }
                }
            }  
        }
        
        for(Segmento segmentoDeLista: controlador.getListas().getListaDeSegmentos()){
            if(segmentoDeLista.getSegmento().equals(version.getSegmento().getSegmento())){
                segmento.setCostoFlete(segmentoDeLista.getCostoFlete());
                segmento.setSegmento(segmentoDeLista.getSegmento());
                segmento.setPatentamiento(version.getSegmento().getPatentamiento());
                break;
            }
        }
        
        for(Version versionL: controlador.getListas().getListaDeVersiones()){
            if(versionL.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                for(Color colorL: version.getColores()){
                    if(colorL.getColor().equals(this.jComboBox4.getSelectedItem())){
                        color.setColor(colorL.getColor());
                        color.setCantidad(colorL.getCantidad());
                    }
                }
            }
         }
        
        String nombre;
        
        for(Cliente clienteLista: controlador.getListas().getListaDeClientes()){
            nombre = clienteLista.getNombre() + " " + clienteLista.getApellido();
            if(nombre.equals(this.jComboBox5.getSelectedItem())){
                cliente.setApellido(clienteLista.getApellido());
                cliente.setCel((long) clienteLista.getCel());
                cliente.setDNI(clienteLista.getDNI());
                cliente.setDireccion(clienteLista.getDireccion());
                cliente.setEmail(clienteLista.getEmail());
                cliente.setNombre(clienteLista.getNombre());
                cliente.setTel((long) clienteLista.getTel());
                break;
            }
        }
        
        Reserva reservaTemp = new Reserva();
        
        reservaTemp.setCliente(cliente);
        reservaTemp.setMarca(marca);
        reservaTemp.setModelo(modelo);
        reservaTemp.setVersion(version);
        reservaTemp.setSegmento(segmento);
        reservaTemp.setColor(color);
        reservaTemp.setFecha(fecha);
        reservaTemp.calcularPrecioFinal();
        
        String detalle=String.format("Cliente: %s %s\n"
                               + "Fecha: %s\n"
                               + "Marca: %s\n"
                               + "Modelo: %s\n"
                               + "Version: %s\n"
                               + "Color: %s\n"
                               + "Segmento: %s\n"
                               + "Precio Unidad: $ %.2f\n"
                               + "Precio Flete: $ %.2f\n"
                               + "Precio Patentamiento: $ %.2f\n"
                               + "TOTAL: $ %.2f\n\n",
                cliente.getApellido(), cliente.getNombre(), fecha.toString(), marca.getMarca(),
                modelo.getModelo(), version.getDescripcion(), color.getColor(), segmento.getSegmento(),
                version.getPrecioUnidad(), segmento.getCostoFlete(), segmento.getPatentamiento(),
                reservaTemp.getPrecioFinal()); 

        int a = JOptionPane.showConfirmDialog(null, detalle + "¿Desea confirmar la reserva?", 
                "Confirmar Reserva", JOptionPane.YES_NO_OPTION, 
		JOptionPane.INFORMATION_MESSAGE); 
        
        if(a == JOptionPane.YES_OPTION){
            reservaTemp.setEstado("Pendiente");
            controlador.getListas().getListaDeReservas().add(reservaTemp);
            for(Version versionDeLista: controlador.getListas().getListaDeVersiones()){
                if(versionDeLista.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                    for(Color colorLista: versionDeLista.getColores()){
                        if(colorLista.getColor().equals(this.jComboBox4.getSelectedItem())){
                            int indice1 = controlador.getListas().getListaDeVersiones().indexOf(versionDeLista);
                            int indice2 = controlador.getListas().getListaDeVersiones().get(indice1).getColores().indexOf(colorLista);
                            controlador.getListas().getListaDeVersiones().get(indice1).getColores().get(indice2).setCantidad(
                            controlador.getListas().getListaDeVersiones().get(indice1).getColores().get(indice2).getCantidad() - 1);
                        }
                    }
                }
            }
            
            JOptionPane.showConfirmDialog(null, "La reserva se almacenó correctamente.",
                "Rerseva almacenada", JOptionPane.CLOSED_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
            
            this.jComboBox5.setSelectedIndex(0);
            this.jComboBox4.setSelectedIndex(0);
            this.jComboBox3.setSelectedIndex(0);
            this.jComboBox2.setSelectedIndex(0);
            this.jComboBox1.setSelectedIndex(0);
            this.jTextField3.setText("");
        }
        if(a == JOptionPane.NO_OPTION){
            reservaTemp.setEstado("Rechazado");
            controlador.getListas().getListaDeReservas().add(reservaTemp);
            JOptionPane.showConfirmDialog(null, "La reserva ha sido rechazada.",
                "Rerseva rechazada", JOptionPane.CLOSED_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
            this.jComboBox5.setSelectedIndex(0);
            this.jComboBox4.setSelectedIndex(0);
            this.jComboBox3.setSelectedIndex(0);
            this.jComboBox2.setSelectedIndex(0);
            this.jComboBox1.setSelectedIndex(0);
            this.jTextField3.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(this.jComboBox5.getSelectedItem() == null){
            this.jButton1.setEnabled(false);
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox2.setSelectedIndex(0);
                this.jComboBox2.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox1.setSelectedIndex(0);
                this.jComboBox1.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            this.jLabel9.setText("");
            return;
        }
        
        else if(this.jComboBox5.getSelectedItem().equals("")){
            this.jButton1.setEnabled(false);
            this.jLabel9.setText("");
            this.jLabel10.setVisible(false);
            this.jLabel11.setVisible(false);
            this.jLabel12.setVisible(false);
            this.jLabel13.setVisible(false);
            
            try{
                this.jComboBox4.setSelectedIndex(0);
                this.jComboBox4.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox3.setSelectedIndex(0);
                this.jComboBox3.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox2.setSelectedIndex(0);
                this.jComboBox2.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            
            try{
                this.jComboBox1.setSelectedIndex(0);
                this.jComboBox1.setEnabled(false);
            }
            catch(java.lang.IllegalArgumentException ex){}
            return;
        }
        this.jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            return;
        }
        if(evt.getKeyCode() == KeyEvent.VK_SLASH){
            this.jTextField3.setText(this.jTextField3.getText().replace("/", ""));
            return;
        }
        if(this.jTextField3.getText().length() == 2){
            this.jTextField3.setText(this.jTextField3.getText() + "/");
        }
        if(this.jTextField3.getText().length() == 5){
            this.jTextField3.setText(this.jTextField3.getText() + "/");
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    public void cerradoCliente(){
        String nombre;
        String apellido;
        String completo;
        nombre = this.controlador.getListas().getListaDeClientes().get(this.controlador.getListas().getListaDeClientes().size() - 1).getNombre();
        apellido = this.controlador.getListas().getListaDeClientes().get(this.controlador.getListas().getListaDeClientes().size() - 1).getApellido();
        completo = nombre + " " + apellido;

        if(!this.jComboBox5.getItemAt(this.jComboBox5.getItemCount() - 1).equals(completo)){
            this.jComboBox5.addItem(completo);
        }
    }
    
    public void cerradoVehiculo(Version versionN, Marca marcaN, boolean nuevaMarca, boolean nuevoModelo, boolean nuevaVersion){
        
        if(nuevaMarca){
            this.jComboBox1.addItem(marcaN.getMarca());
            this.jComboBox3.addItem(versionN.getModelo().getModelo());
            this.jComboBox2.addItem(versionN.getDescripcion());
        }
        else if (nuevoModelo){
            this.jComboBox3.addItem(versionN.getModelo().getModelo());
            this.jComboBox2.addItem(versionN.getDescripcion());
        }
        else if (nuevaVersion){
            this.jComboBox2.addItem(versionN.getDescripcion());
        }
        else{
            this.actualizarColores();
        }
    }
    
    private void actualizarColores(){
        this.jComboBox4.removeAllItems();
        this.jComboBox4.addItem("");
        
        for(Version version: controlador.getListas().getListaDeVersiones()){
            if(version.getDescripcion().equals(this.jComboBox3.getSelectedItem())){
                for(Color color: version.getColores()){
                    if(color.getCantidad() > 0){
                        this.jComboBox4.addItem(color.getColor());
                    }
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaReserva(new Controlador()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
